permalink   : /:categories/:year/:title/
markdown    : kramdown
highlighter : pygments

paginate: 2 #6
comments: true
paginate_path: "/page/:num"

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed

# Site settings
title: aBraincode
description: "Web and Mobile Developer"
email: aBraincode@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://yourdomain.com"
url: "https://abraincode.github.io"
repository: "https://github.com/abraincode/abraincode.github.io"
disqus_shortname: "mimin"

# social footer
social:
  github:
    slug: github
    link: http://github.com/abraincode
  facebook:
    slug: facebook
    link: ""
  twitter:
    slug: twitter
    link: ""
  instagram:
    slug: instagram
    link: ""
  linkedin:
    slug: linkedin
    link: ""
